# Generated by Django 4.1.5 on 2023-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='images/captain-america.jpg', null=True, upload_to='images/', verbose_name='Profile pic'),
        ),
    ]
