# Generated by Django 4.1.5 on 2023-04-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='topic_name',
        ),
    ]
