# Generated by Django 4.1.5 on 2023-06-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztopic',
            name='image',
            field=models.ImageField(default='captain-america.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='image',
            field=models.ImageField(default='captain-america.jpg', upload_to='images/'),
        ),
    ]
